services:
  wwords:
    build: .
    container_name: wwords
    ports:
      - "7997:7997"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/data.db}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
